### ISSUE TITLE
Missging "calculation" trigger of the feature "Generate data from an expression"

### ISSUE THREAD

**Issue by Real-MJoe** [prb28/vscode-amiga-assembly#69]
Hello,

if i use the feature "Generate data from an expression" on my second System the link" Generate Data" over the "generated-datagen" is still missing. 

![image](https://user-images.githubusercontent.com/40276633/58476939-91819200-8152-11e9-9798-e2deccdd09a0.png)

All is up to date. Where can i check some error logs or so.

regard joe

**Comment by prb28** [comment]
Strange, you may have some logs in the output window, select "Amiga Assembly" in the combo:
![Output window](https://user-images.githubusercontent.com/10462286/58503119-45e9db00-8188-11e9-97bf-a04d62d18682.png)

**Comment by Real-MJoe** [comment]
My logs look like this:

Amiga Assembly:
![image](https://user-images.githubusercontent.com/40276633/58535431-4917b200-81ee-11e9-823a-3496175811e7.png)

Log(Extension host):
![image](https://user-images.githubusercontent.com/40276633/58535451-546add80-81ee-11e9-9c2c-0ee5e953ef2c.png)

Browser log:
![image](https://user-images.githubusercontent.com/40276633/58535497-72d0d900-81ee-11e9-834a-303d435b8fe4.png)

**Comment by prb28** [comment]
The error log was not related to this issue, I've fixed it but it's not a solution.
Could you please install the last [beta binary](https://github.com/prb28/vscode-amiga-assembly/releases/download/0.17.0-b4/amiga-assembly-0.17.0.vsix) ?
And try the command: press F1 and select the command **Amiga Assembly: Generate data from expression**

**Comment by Real-MJoe** [comment]
So the link" Generate Data" still isn't there. But the command "Amiga Assembly: Generate data from expression" works now. :) 

**Other Bug**;
After each creation of the data a blank line is created after the tag ";@generated-datagen-end----------------".

**Comment by prb28** [comment]
I've added issue: #72 .

For this issue, two more questions: 
- which OS do you use?
- do you have some **vscode settings** different between the two environment?
There is a setting to enable/disable it: "Controls whether the editor shows CodeLens"

**Comment by prb28** [comment]
Excellent!
With the user/workspace/folder settings sometimes it's tricky to understand what's going on.
So, may we close this one?

**Comment by Real-MJoe** [comment]
From my side, this can be closed. It is not a real bug, rather a user bug. ;)
